### ISSUE TITLE
每页文章数量设置过小时，在电脑端不能触发滚动

### ISSUE THREAD

**Issue by 0-RTT** [fordes123/typecho-theme-pic-r#2]
每页文章数量设置过小时，在电脑端不能触发滚动，也没有滚动条。手机端正常。

**Comment by fordes123** [comment]
建议设置大一点，如果不显示滚动条自然不会触发滚动加载

**Comment by 0-RTT** [comment]
> 建议设置大一点，如果不显示滚动条自然不会触发滚动加载

设置大的话感觉影响打开网页的速度，需要加载图片

**Comment by fordes123** [comment]
已添加图片懒加载 提高首页加载速度
