### ISSUE TITLE
在修改站点地址后主题一直载不进去

### ISSUE THREAD

**Issue by cgqhegl** [fordes123/typecho-theme-pic-r#6]
在修改站点地址后主题一直载不进去，127.0.0.1和localhost不受影响，但是一换到本机IP就不行，但是其他主题不收影响是怎么回事。

**Comment by fordes123** [comment]
和主题无关，建议检查一下 nginx 伪静态配置 和 typecho 设置 -> 永久链接 -> 地址重写
